marques_autres = [
    'Nike',
    'Pier One',
    'Polo Ralph Lauren',
    'Lacoste',
    'Tommy Hilfiger',
    'Jack & Jones',
    'YOURTURN',
    'adidas',
    'Levi\'s®',
    'PULL&BEAR',
    'Bershka',
    'Carhartt WIP',
    'BOSS',
    'Mango',
    'Under Armour',
    'Calvin Klein',
    'HUGO',
    'The North Face',
    'C&A',
    'Only & Sons',
    'Superdry',
    'Puma',
    'K-Way',
    'Dickies',
    'Isaac Dewhirst',
    'INDICODE JEANS',
    'Urban Classics',
    'G-Star',
    'GAP',
    'New Balance',
    'Hollister Co',
    'Vans',
    'Karl Kani',
    'SIKSILK',
    'Abercrombie & Fitch',
    'Next',
    'Redefined Rebel',
    'Columbia',
    'Brave Soul',
    'Mister Tee',
    'Ellesse',
    'Diesel',
    'Schott',
    'EA7 Emporio Armani',
    'Alessandro Zavetti',
    'EIGHTYFIVE',
    'Pepe Jeans',
    'CLOSURE London',
    'Napapijri',
    'Marks & Spencer',
    'Champion',
    'Armani Exchange',
    'OppoSuits',
    'Timberland',
    'GANT',
    'Fila',
    'Sixth June',
    'Rains',
    'Lyle & Scott',
    'The Kooples',
    'Emporio Armani',
    'JOTT',
    'Brandit',
    'Williot',
    'WRSTBHVR',
    'Selected Homme',
    'Santa Cruz',
    'Petrol Industries',
    'Lee',
    'Kaotiko',
    'Glorious Gangsta',
    'Alpha Industries',
    'ASICS',
    'Pegador',
    'KARL LAGERFELD',
    'Happy Socks',
    'Guess',
    'Converse',
    'CHASIN\'',
    'WE Fashion',
    'Multiply Apparel',
    'Lindbergh',
    'Kappa',
    'Jacker',
    'Edwin',
    'DOCKERS',
    'America Today',
    's.Oliver',
    'Wrangler',
    'Wasted Paris',
    'Volcom',
    'Twisted Tailor',
    'TOM TAILOR DENIM',
    'Scotch & Soda',
    'Reebok',
    'New Era',
    'MJ Gonzales',
    'Kings Will Dream',
    'Hummel',
    'HUF',
    'Gabbiano',
    'Danish Endurance',
    'DIM',
    'Bombers',
    'Antioch',
    'ARKET',
    '274',
    'lululemon',
    'le coq sportif',
    'khujo',
    'iets frans...',
    'Zign Studio',
    'Zadig & Voltaire',
    'Weekday',
    'Venum',
    'Umbro',
    'Trueprodigy',
    'Teddy Smith',
    'Stradivarius',
    'Sergio Tacchini',
    'SNOCKS',
    'Replay',
    'QS by s.Oliver',
    'Project X Paris',
    'Patagonia',
    'Parajumpers',
    'Night Addict',
    'Minimum',
    'Le Temps Des Cerises',
    'LTB',
    'LOW LIGHTS STUDIOS®',
    'Kronstadt',
    'Jaded London',
    'JOOP!',
    'Farah',
    'Fanatics',
    'Esprit',
    'Ed Hardy',
    'DeFacto',
    'Boggi Milano',
    'Billabong',
    'Barbour Beacon',
    'BONOBO Jeans',
    'BDG Urban Outfitters',
    'Armor lux',
    'Antony Morato',
    'AllSaints'
]

for element in marques_autres:
    print("SUM(CASE WHEN marque LIKE '%" + element + "%' THEN 1 ELSE 0 END) AS " + element.replace(" ", "") + ",")